```{r}
link="https://github.com/Vis-Analytics-FinalProj/RawData/raw/main/Seattle_Pet_Licenses%20CLEANED.xlsx"

library(rio)
mydata=import(link)
```

```{r}
str(mydata,width = 150,strict.width='cut')
```
#Hnin's Univariate Plot
```{r}
library(lubridate)
mydata$LicenseIssueDate <- mdy(mydata$`License Issue Date`)
```

```{r}
# key change
mydata$LicenseIssueDate=floor_date(mydata$LicenseIssueDate,"month")

```

```{r}
head(mydata)
```

```{r}
DFissue=as.data.frame(table(mydata$LicenseIssueDate), stringsAsFactors =FALSE)
names(DFissue)=c("date","Count")
#key change!
DFissue$date=as.Date(DFissue$date)
```

```{r}
head(DFissue)
```

NEW!- plot

```{r}
library(ggplot2)
base1=ggplot(data=DFissue, aes(x=date,y=Count))
bar1=base1+geom_bar(stat = 'identity')
bar1

```



```{r}
library(ggplot2)
DFissue_sub=DFissue[DFissue$date>=as.Date('2019-02-01'),]
base1=ggplot(data=DFissue_sub, aes(x=date,y=Count))
bar1=base1+geom_bar(stat = 'identity')
bar1

```

```{r}

library(scales)

bar2=bar1 + scale_x_date(breaks = date_breaks("months"),
  labels = date_format("%b-%y"))  + theme_classic()


bar3=bar2 + theme(axis.text.x = element_text(angle = 90)) 


bar3

```


```{r}
bar4=bar3 + geom_text(aes(label=Count),
                      angle=90 ,
                      size=4,
                      hjust = 1,
                      color='white') + geom_vline(xintercept=as.Date('2020-03-23'), col="red") + geom_text(aes(x=as.Date('2020-03-23'), label="Lockdown 3/23/'20", y=2800), color="red", angle=0, size=3) +
  stat_smooth(color = "red",
                      fill = "yellow",
                      method = "loess") 
                
bar4
```

```{r}
Titles=list(Title="All Pet Licenses Purchased in recent years",
            SubTi="2019 January to 2021 January",
            XTi="Month and Year",
            YTi="Count of Pet Licenses",
            Sou="Source: King County")

## placing the titles on the graph
plot5= bar4 + labs(title = Titles$Title,
                    subtitle = Titles$SubTi,
                    x=Titles$XTi,
                    y=Titles$YTi,
                    caption = Titles$Sou)
plot5

```

#Hnin's Bivariate Plot
```{r}
head(mydata$`License Issue Date`,20)
```

```{r}
dfwaffle=as.data.frame(table(mydata$LicenseIssueDate, mydata$Species), stringsAsFactors =FALSE)
names(dfwaffle)=c("date","species","Count")
#key change!
#dfwaffle$date=as.Date(dfwaffle$date)
dfwaffle$date = format(as.Date(dfwaffle$date, format="%Y-%m-%d"),"%Y")
```

```{r}
head(dfwaffle,50)
```

```{r}
library(dplyr)
library(waffle)

dfwaffle %>% 
  filter(date >= 2018) %>% 
  count(date, species, Count) -> dfwaffle_date
  
ggplot(dfwaffle_date, aes(fill = species, values = Count/100)) +
  geom_waffle(color = "white", size = 0.25, n_rows = 10, flip = TRUE) +
  facet_wrap(~date, nrow = 1, strip.position = "bottom") +
  scale_x_discrete() + 
  scale_y_continuous(labels = function(x) x * 10, # make this multiplyer the same as n_rows
                     expand = c(0,0))+
  ggthemes::scale_fill_tableau(name=NULL) +
  coord_equal() +
  labs(
    title = "Pet Adoption in Seattle Over the Recent Years",
    subtitle = "2018 to 2021",
    x = "Year",
    y = "Count of Adopted Cats & Dogs in 100"
  ) +
  theme_minimal(base_family = "Roboto Condensed") +
  theme(panel.grid = element_blank(), axis.ticks.y = element_line()) +
  guides(fill = guide_legend(reverse = TRUE))

```

#Hnin's Map Plot
```{r}
linkMap="https://github.com/Vis-Analytics-FinalProj/SeattleZIP/raw/main/King%20County%20ZIP%20Codes.json" # link desde github
library(sf)
```

```{r}
petWorld=read_sf(linkMap)
```

```{r}
head(petWorld)
```


```{r}
head(mydata,3)
```


```{r}
petWorldVars=merge(petWorld, #map first
                   mydata, 
                   by.x='ZIPCODE', by.y='ZIP Code') #to merge the column 
```

```{r}
head(petWorldVars,10)
```

```{r}
summary(petWorldVars$ZIPCODE)
```



Prepare data frame
```{r}
a = table(petWorldVars$ZIPCODE)
b = as.data.frame(a)
names(b)[1] = 'Zip'
b
```

 
```{r}
#Order data by Freq
c = b[order(-b[[2]]),]
c
```

```{r}
#Top 25 zipcodes for adoption.
ToBar=c[order(-c$Freq)[1:52],]
ToBar
```

```{r}
petWorldVars1=merge(petWorldVars, #map first
                   ToBar, 
                   by.x='ZIPCODE', by.y='Zip')
```

```{r}
head(petWorldVars1,10)
```

```{r}
library(ggplot2)
# plot original map
base=ggplot(data=petWorldVars) + geom_sf(fill='grey90',
                                     color=NA) + theme_classic()
base #base map
```

```{r}
colMap = base + geom_sf(data=petWorldVars1, aes(fill=-Freq),
                       color=NA) + theme_classic()
colMap
```

```{r}
SeaMap = colMap + scale_fill_gradient(low = 'red',
                             high= 'blue')

SeaMap
```

## Adding title names
```{r}
Titles=list(Title="All Pet Licenses Purchased in King County by ZIP Code",
            SubTi="2015-2019",
            Sou="Source: King County")
```

```{r}
plot2= SeaMap + labs(title = Titles$Title,
                    subtitle = Titles$SubTi,
                    caption = Titles$Sou)

plot3 = plot2 + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())


bartext=plot3 + labs(fill = "Count")

MapChart = bartext + theme(
  plot.title = element_text(hjust = 0.5),
  plot.subtitle = element_text(hjust = 0.5)
)
MapChart
```

