#Hnin's Univariate Plot Begins Here

```{r}
link="https://github.com/Vis-Analytics-FinalProj/RawData/raw/main/Seattle_Pet_Licenses%20CLEANED.xlsx"

library(rio)
mydata=import(link)

library(lubridate)
mydata$LicenseIssueDate <- mdy(mydata$`License Issue Date`)

mydata$LicenseIssueDate=floor_date(mydata$LicenseIssueDate,"month")

DFissue=as.data.frame(table(mydata$LicenseIssueDate), stringsAsFactors =FALSE)
names(DFissue)=c("date","Count")

DFissue$date=as.Date(DFissue$date)

library(ggplot2)
base1=ggplot(data=DFissue, aes(x=date,y=Count))
bar1=base1+geom_bar(stat = 'identity')

library(ggplot2)
DFissue_sub=DFissue[DFissue$date>=as.Date('2019-02-01'),]
base1=ggplot(data=DFissue_sub, aes(x=date,y=Count))
bar1=base1+geom_bar(stat = 'identity')

library(scales)

bar2=bar1 + scale_x_date(breaks = date_breaks("months"),
  labels = date_format("%b-%y"))  + theme_classic()

bar3=bar2 + theme(axis.text.x = element_text(angle = 90)) 

bar4=bar3 + geom_text(aes(label=Count),
                      angle=90 ,
                      size=4,
                      hjust = 1,
                      color='white') + geom_vline(xintercept=as.Date('2020-03-23'), col="red") + geom_text(aes(x=as.Date('2020-03-23'), label="Lockdown 3/23/'20", y=2800), color="red", angle=0, size=3) +
  geom_smooth(formula = y ~ x, method = "loess", mapping = NULL, data = NULL, stat = "smooth", position = "identity",color = "red", fill = "yellow") 
                
Titles=list(Title="All Pet Licenses Purchased in recent years",
            SubTi="2019 January to 2021 January",
            XTi="Month and Year",
            YTi="Count of Pet Licenses",
            Sou="Source: King County")

bar5= bar4 + labs(title = Titles$Title,
                    subtitle = Titles$SubTi,
                    x=Titles$XTi,
                    y=Titles$YTi,
                    caption = Titles$Sou)
bar5

```
#Hnin's Bivariate Plot Begins Here
```{r}

dfwaffle=as.data.frame(table(mydata$LicenseIssueDate, mydata$Species), stringsAsFactors =FALSE)
names(dfwaffle)=c("date","species","Count")
dfwaffle$date = format(as.Date(dfwaffle$date, format="%Y-%m-%d"),"%Y")

library(dplyr)
library(waffle)

dfwaffle %>% 
  filter(date >= 2018) %>% 
  count(date, species, Count) -> dfwaffle_date
  
ggplot(dfwaffle_date, aes(fill = species, values = Count/100)) +
  geom_waffle(color = "white", size = 0.25, n_rows = 10, flip = TRUE) +
  facet_wrap(~date, nrow = 1, strip.position = "bottom") +
  scale_x_discrete() + 
  scale_y_continuous(labels = function(x) x * 10, # make this multiplyer the same as n_rows
                     expand = c(0,0))+
  ggthemes::scale_fill_tableau(name=NULL) +
  coord_equal() +
  labs(
    title = "Pet Adoption in Seattle Over the Recent Years",
    subtitle = "Each square representing 100",
    x = "Year",
    y = "Count of Adopted Cats & Dogs in 100s"
  ) +
  theme_minimal(base_family = "Roboto Condensed") +
  theme(panel.grid = element_blank(), axis.ticks.y = element_line()) +
  guides(fill = guide_legend(reverse = TRUE))

```

#Hnin's Map Plot Begins Here
```{r}
linkMap="https://github.com/Vis-Analytics-FinalProj/Rebecca-Taylor/raw/main/Zipcodes_for_King_County_and_Surrounding_Area___zipcode_area%20(1).json"
library(sf)

petWorld=read_sf(linkMap)

petWorldVars=merge(petWorld, #map first
                   mydata, 
                   by.x='ZIPCODE', by.y='ZIP Code') #to merge the column 

a = table(petWorldVars$ZIPCODE)
b = as.data.frame(a)
names(b)[1] = 'Zip'

c = b[order(-b[[2]]),]

ToBar=c[order(-c$Freq)[1:52],]

petWorldVars1=merge(petWorldVars, #map first
                   ToBar, 
                   by.x='ZIPCODE', by.y='Zip')

library(ggplot2)
base=ggplot(data=petWorldVars) + geom_sf(fill='grey90', color='grey40', lwd=0.5) + theme_classic()

colMap = base + geom_sf(data=petWorldVars1, aes(fill=-Freq), 
                      color="grey40", lwd=0.25)+ scale_fill_viridis_c(option = "magma",begin = 0.1)

rgbMap = colMap + scale_fill_gradient(low = 'red',
                             high= 'blue') 

ZipMap = rgbMap + geom_point(aes(x=-122.29180, y=47.68676), size=2, color="white") +
  geom_text(x=-122.13, y=47.7, label="98115", size=4, color="white")

Titles=list(Title="All Pet Licenses Purchased in King County by ZIP Code",
            SubTi="With Most Licenses at 98115",
            Sou="Source: 2015-2019 King County")


final1= ZipMap + labs(title = Titles$Title,
                    subtitle = Titles$SubTi,
                    caption = Titles$Sou)

final2 = final1 + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

bartext=final2 + labs(fill = "Count")

final3 = bartext + theme(
  plot.title = element_text(hjust = 0.5),
  plot.subtitle = element_text(hjust = 0.5)
)

final3
```


